### PR TITLE
data_sciences_campaign_license

### PR DESCRIPTION
**Pull request by batermj**
All Rights Reserved.

### CODE REVIEW

**Comment by ytrezq** [comment]
@batermj hello I saw you are [one of](https://gist.github.com/ytrezq/b88bfb074b70885cd543/stargazers) my [followers](https://gist.github.com/ytrezq/b88bfb074b70885cd543). Can you please send your e-mail ? I have a few question for you.

**Comment by batermj** [comment]
@ytrezq , please write questions here, that is ok for me:)

**Comment by ytrezq** [comment]
@batermj the problem is I’m wanting to talk about content which shouldn’t be public yet.

**Comment by ytrezq** [comment]
@batermj So I can’t talk about it here. Can you please send your e-mail ?

**Comment by batermj** [comment]
> @batermj So I can’t talk about it here. Can you please send your e-mail ?

**Comment by batermj** [comment]
you can send me private msg on linkedin, my name is bater.makhabel.

**Comment by ytrezq** [comment]
@batermj : sorry but unless paid for a bug I don’t create accounts on things like bboards or so called social networks.
So I won’t go on Linkedin. An alternative is needed.

**Pull request closed without merging**
